import type { AudioPreset, Language } from './types';

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English (US)', flag: '🇺🇸' },
  { code: 'en-IN', name: 'English (India)', flag: '🇮🇳' },
  { code: 'hi', name: 'Hindi', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', flag: '🇧🇩' },
  { code: 'ta', name: 'Tamil', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', flag: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', flag: '🇮🇳' },
  { code: 'gu', name: 'Gujarati', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', flag: '🇮🇳' },
  { code: 'es', name: 'Spanish', flag: '🇪🇸' },
  { code: 'fr', name: 'French', flag: '🇫🇷' },
  { code: 'de', name: 'German', flag: '🇩🇪' },
  { code: 'it', name: 'Italian', flag: '🇮🇹' },
  { code: 'pt', name: 'Portuguese', flag: '🇵🇹' },
  { code: 'ru', name: 'Russian', flag: '🇷🇺' },
  { code: 'ja', name: 'Japanese', flag: '🇯🇵' },
  { code: 'ko', name: 'Korean', flag: '🇰🇷' },
  { code: 'zh', name: 'Chinese', flag: '🇨🇳' },
  { code: 'ar', name: 'Arabic', flag: '🇸🇦' },
];

export const EMOTIONS = [
  { value: 'neutral', label: 'Neutral', description: 'Balanced and professional tone' },
  { value: 'excited', label: 'Excited', description: 'Energetic and enthusiastic delivery' },
  { value: 'calm', label: 'Calm', description: 'Relaxed and soothing narration' },
  { value: 'serious', label: 'Serious', description: 'Authoritative and formal tone' },
  { value: 'playful', label: 'Playful', description: 'Fun and lighthearted approach' },
];

export const THEMES = [
  { value: 'none', label: 'No Music', description: 'Pure voice narration' },
  { value: 'upbeat', label: 'Upbeat', description: 'Positive and energetic background' },
  { value: 'dramatic', label: 'Dramatic', description: 'Intense and impactful atmosphere' },
  { value: 'corporate', label: 'Corporate', description: 'Professional business tone' },
  {
    value: 'inspirational',
    label: 'Inspirational',
    description: 'Motivating and uplifting mood',
  },
];

export const DEFAULT_AUDIO_SETTINGS = {
  tempo: 1.0,
  emotion: 'neutral' as const,
  theme: 'none' as const,
  volume: 80,
  pitch: 1.0,
  musicVolume: 30,
  voiceClarity: 75,
  backgroundNoise: 0,
  voiceMode: 'normal' as const,
  ttsEngine: 'chatterbox' as const,
  googleVoicePreset: 'chirp_female',
  googleSpeakingRate: 1.0,
  googlePitch: 0.0,
  googleEnableSSML: false,
};

export const GOOGLE_VOICE_PRESETS = [
  {
    id: 'chirp_female',
    name: 'Chirp Female (HD)',
    description: 'Premium AI voice - Best quality, most natural',
    quality: 5,
    cost: '$30/1M chars',
    category: 'Premium',
    languages: ['en'],
  },
  {
    id: 'chirp_male',
    name: 'Chirp Male (HD)',
    description: 'Premium AI voice - Best quality, most natural',
    quality: 5,
    cost: '$30/1M chars',
    category: 'Premium',
    languages: ['en'],
  },
  {
    id: 'neural_expressive',
    name: 'Neural Expressive',
    description: 'Warmest, most expressive female voice',
    quality: 5,
    cost: '$16/1M chars',
    category: 'High Quality',
    languages: ['en', 'en-IN', 'hi', 'es', 'fr', 'de', 'it', 'pt', 'ja', 'ko'],
  },
  {
    id: 'neural_female',
    name: 'Neural Female',
    description: 'Clear conversational voice',
    quality: 4,
    cost: '$16/1M chars',
    category: 'High Quality',
    languages: ['en', 'en-IN', 'hi', 'es', 'fr', 'de', 'it', 'pt', 'ja', 'ko', 'zh', 'ar'],
  },
  {
    id: 'neural_male',
    name: 'Neural Male',
    description: 'High-quality professional voice',
    quality: 4,
    cost: '$16/1M chars',
    category: 'High Quality',
    languages: ['en', 'en-IN', 'hi', 'es', 'fr', 'de', 'it', 'pt', 'ja', 'ko', 'zh', 'ar'],
  },
  {
    id: 'journey_female',
    name: 'Journey Female',
    description: 'Conversational and engaging',
    quality: 4,
    cost: '$16/1M chars',
    category: 'Conversational',
    languages: ['en'],
  },
  {
    id: 'wavenet_female',
    name: 'WaveNet Female',
    description: 'Budget-friendly, good quality',
    quality: 3,
    cost: '$4/1M chars',
    category: 'Budget',
    languages: [
      'en',
      'en-IN',
      'hi',
      'bn',
      'ta',
      'te',
      'ml',
      'kn',
      'gu',
      'mr',
      'es',
      'fr',
      'de',
      'it',
      'pt',
      'ja',
      'ko',
      'zh',
      'ar',
      'ru',
    ],
  },
  {
    id: 'wavenet_male',
    name: 'WaveNet Male',
    description: 'Budget-friendly, good quality',
    quality: 3,
    cost: '$4/1M chars',
    category: 'Budget',
    languages: [
      'en',
      'en-IN',
      'hi',
      'bn',
      'ta',
      'te',
      'ml',
      'kn',
      'gu',
      'mr',
      'es',
      'fr',
      'de',
      'it',
      'pt',
      'ja',
      'ko',
      'zh',
      'ar',
      'ru',
    ],
  },
];

// Helper function to get voice presets for a specific language
export function getVoicePresetsForLanguage(
  language: string,
  ttsEngine: 'chatterbox' | 'google' = 'google',
) {
  if (ttsEngine === 'chatterbox') {
    // ChatterBox currently only supports English
    return language === 'en' ? GOOGLE_VOICE_PRESETS : [];
  }

  // Filter Google TTS presets by language
  return GOOGLE_VOICE_PRESETS.filter((preset) => preset.languages?.includes(language) ?? false);
}

export const AUDIO_PRESETS: AudioPreset[] = [
  {
    id: 'podcast',
    name: 'Podcast',
    description: 'Clear voice with minimal background',
    icon: '🎙️',
    settings: {
      tempo: 1.0,
      emotion: 'neutral',
      theme: 'none',
      volume: 85,
      pitch: 1.0,
      musicVolume: 0,
      voiceClarity: 90,
      backgroundNoise: 0,
    },
  },
  {
    id: 'tutorial',
    name: 'Tutorial',
    description: 'Slower pace with corporate background',
    icon: '📚',
    settings: {
      tempo: 0.9,
      emotion: 'calm',
      theme: 'corporate',
      volume: 80,
      pitch: 1.0,
      musicVolume: 20,
      voiceClarity: 85,
      backgroundNoise: 0,
    },
  },
  {
    id: 'promo',
    name: 'Promo',
    description: 'Energetic with upbeat music',
    icon: '🚀',
    settings: {
      tempo: 1.2,
      emotion: 'excited',
      theme: 'upbeat',
      volume: 90,
      pitch: 1.05,
      musicVolume: 45,
      voiceClarity: 80,
      backgroundNoise: 0,
    },
  },
  {
    id: 'documentary',
    name: 'Documentary',
    description: 'Serious tone with dramatic music',
    icon: '🎬',
    settings: {
      tempo: 0.95,
      emotion: 'serious',
      theme: 'dramatic',
      volume: 85,
      pitch: 0.95,
      musicVolume: 35,
      voiceClarity: 85,
      backgroundNoise: 5,
    },
  },
  {
    id: 'meditation',
    name: 'Meditation',
    description: 'Calm and soothing atmosphere',
    icon: '🧘',
    settings: {
      tempo: 0.8,
      emotion: 'calm',
      theme: 'inspirational',
      volume: 70,
      pitch: 0.98,
      musicVolume: 40,
      voiceClarity: 80,
      backgroundNoise: 10,
    },
  },
  {
    id: 'vlog',
    name: 'Vlog',
    description: 'Casual and playful style',
    icon: '📹',
    settings: {
      tempo: 1.1,
      emotion: 'playful',
      theme: 'upbeat',
      volume: 85,
      pitch: 1.02,
      musicVolume: 30,
      voiceClarity: 75,
      backgroundNoise: 0,
    },
  },
];
