'use client';

import type { VoicePresetCreateRequest } from './voice-preset-types';

// Curated, production-ready ChatterBox TTS presets
export const RECOMMENDED_PRESETS: VoicePresetCreateRequest[] = [
  {
    name: 'Natural Narrator',
    description: 'Neutral, clear narration for general content',
    isPublic: false,
    exaggeration: 0.28,
    cfgWeight: 0.62,
    temperature: 0.28,
    repetitionPenalty: 1.2,
    speed: 0.98,
    seed: 42,
    language: 'en',
    targetWpm: 155,
  },
  {
    name: 'Conversational YouTuber',
    description: 'Friendly, upbeat conversational delivery for YouTube videos',
    isPublic: false,
    exaggeration: 0.42,
    cfgWeight: 0.58,
    temperature: 0.35,
    repetitionPenalty: 1.25,
    speed: 1.05,
    seed: 42,
    language: 'en',
    targetWpm: 165,
  },
  {
    name: 'Crisp Explainer',
    description: 'Precise articulation for explainers and product demos',
    isPublic: false,
    exaggeration: 0.2,
    cfgWeight: 0.68,
    temperature: 0.22,
    repetitionPenalty: 1.1,
    speed: 1.02,
    seed: 42,
    language: 'en',
    targetWpm: 170,
  },
  {
    name: 'Warm Storyteller',
    description: 'Expressive, warm story narration',
    isPublic: false,
    exaggeration: 0.5,
    cfgWeight: 0.55,
    temperature: 0.32,
    repetitionPenalty: 1.3,
    speed: 0.95,
    seed: 42,
    language: 'en',
    targetWpm: 145,
  },
  {
    name: 'Corporate Neutral',
    description: 'Professional, neutral tone for corporate voiceovers',
    isPublic: false,
    exaggeration: 0.18,
    cfgWeight: 0.72,
    temperature: 0.18,
    repetitionPenalty: 1.05,
    speed: 1.0,
    seed: 42,
    language: 'en',
    targetWpm: 150,
  },
  {
    name: 'Energetic Promo',
    description: 'High-energy promo reads with punch',
    isPublic: false,
    exaggeration: 0.65,
    cfgWeight: 0.5,
    temperature: 0.42,
    repetitionPenalty: 1.35,
    speed: 1.15,
    seed: 42,
    language: 'en',
    targetWpm: 185,
  },
  {
    name: 'Calm Tutorial',
    description: 'Relaxed pace and clarity for step-by-step tutorials',
    isPublic: false,
    exaggeration: 0.22,
    cfgWeight: 0.65,
    temperature: 0.22,
    repetitionPenalty: 1.1,
    speed: 0.96,
    seed: 42,
    language: 'en',
    targetWpm: 140,
  },
  {
    name: 'Podcast Host',
    description: 'Balanced presence for podcast-style delivery',
    isPublic: false,
    exaggeration: 0.38,
    cfgWeight: 0.6,
    temperature: 0.3,
    repetitionPenalty: 1.2,
    speed: 0.98,
    seed: 42,
    language: 'en',
    targetWpm: 155,
  },
  {
    name: 'Audiobook Dramatic',
    description: 'More emotive, dynamic range for fiction audiobooks',
    isPublic: false,
    exaggeration: 0.7,
    cfgWeight: 0.5,
    temperature: 0.4,
    repetitionPenalty: 1.4,
    speed: 0.92,
    seed: 42,
    language: 'en',
    targetWpm: 145,
  },
  {
    name: 'Character Subtle',
    description: 'Light character color without caricature',
    isPublic: false,
    exaggeration: 0.55,
    cfgWeight: 0.52,
    temperature: 0.4,
    repetitionPenalty: 1.35,
    speed: 1.0,
    seed: 42,
    language: 'en',
    targetWpm: 150,
  },
];

// Guardrails:
// - Keep temperature <= 0.4 for stability
// - Keep cfgWeight 0.55–0.72 to stay on-voice but not robotic
// - Use repetitionPenalty 1.1–1.35 for healthy prosody
// - Keep speed within 0.92–1.15 for natural pacing
// - targetWpm reflects the intended delivery style
